In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('data.csv', header = None)

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       5000 non-null   object
 1   1       5000 non-null   int64 
 2   2       5000 non-null   int64 
 3   3       5000 non-null   int64 
 4   4       5000 non-null   int64 
 5   5       5000 non-null   int64 
 6   6       5000 non-null   int64 
 7   7       5000 non-null   int64 
 8   8       5000 non-null   object
dtypes: int64(7), object(2)
memory usage: 351.7+ KB


In [4]:
dataset.head()

0  1    2   3   4  5   6  7       8
0  Saturday  6   32  21  38  9  24  1  Normal
1  Saturday  6  103  36  16  2  12  1  Normal
2    Sunday  7   79  21  15  8  14  1  Normal
3    Sunday  7   65  13  40  5  15  1  Normal
4  Saturday  6   93  36  20  4  16  1  Normal

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       5000 non-null   object
 1   1       5000 non-null   int64 
 2   2       5000 non-null   int64 
 3   3       5000 non-null   int64 
 4   4       5000 non-null   int64 
 5   5       5000 non-null   int64 
 6   6       5000 non-null   int64 
 7   7       5000 non-null   int64 
 8   8       5000 non-null   object
dtypes: int64(7), object(2)
memory usage: 351.7+ KB


In [6]:
missing_data = dataset.isnull().sum()
print(missing_data)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64


In [7]:
dataset[8].value_counts()

Move On    1000
Heavy      1000
Busy       1000
Normal     1000
Worst      1000
Name: 8, dtype: int64

In [8]:
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
dataset[8]= label_encoder.fit_transform(dataset[8])

In [9]:
dataset[8].unique()

array([3, 2, 0, 1, 4])

In [10]:
dataset.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')

In [11]:
print(dataset.shape)

(5000, 9)


In [37]:
X = dataset.iloc[:, 1:8]
y = dataset.iloc[:,8]

In [38]:
X

1    2   3   4  5   6  7
0     6   32  21  38  9  24  1
1     6  103  36  16  2  12  1
2     7   79  21  15  8  14  1
3     7   65  13  40  5  15  1
4     6   93  36  20  4  16  1
...  ..  ...  ..  .. ..  .. ..
4995  5  130  45  45  5  20  0
4996  7   90   4   8  2  20  1
4997  2   32  21  11  8  30  0
4998  6   74  33  12  3   5  1
4999  7   36  34  33  8  21  1

[5000 rows x 7 columns]

In [39]:
y

0       3
1       3
2       3
3       3
4       3
       ..
4995    4
4996    4
4997    4
4998    4
4999    4
Name: 8, Length: 5000, dtype: int64

In [40]:
from keras.models import Sequential

In [41]:
from keras.layers import Dense

In [42]:
from keras.optimizers import Adam

In [43]:
model = Sequential()

In [44]:
model.add(Dense(units=12, input_dim=7, activation='relu') )

In [45]:
model.add(Dense(units=1, activation='sigmoid'))

In [46]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 12)                96        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 13        
Total params: 109
Trainable params: 109
Non-trainable params: 0
_________________________________________________________________


In [47]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [48]:
model.fit(X, y, epochs=160)

Epoch 1/160
157/157 [==============================] - 0s 2ms/step - loss: 59.1368 - accuracy: 0.1924
Epoch 2/160
157/157 [==============================] - 0s 2ms/step - loss: -29.5301 - accuracy: 0.2004
Epoch 3/160
157/157 [==============================] - 0s 2ms/step - loss: -101.0431 - accuracy: 0.2000
Epoch 4/160
157/157 [==============================] - 0s 2ms/step - loss: -205.7520 - accuracy: 0.2000
Epoch 5/160
157/157 [==============================] - 0s 2ms/step - loss: -344.0164 - accuracy: 0.2000
Epoch 6/160
157/157 [==============================] - 0s 2ms/step - loss: -514.5458 - accuracy: 0.2000
Epoch 7/160
157/157 [==============================] - 0s 2ms/step - loss: -715.4430 - accuracy: 0.2000
Epoch 8/160
157/157 [==============================] - 0s 2ms/step - loss: -944.3438 - accuracy: 0.2000
Epoch 9/160
157/157 [==============================] - 0s 2ms/step - loss: -1199.0521 - accuracy: 0.2000
Epoch 10/160
157/157 [==============================] - 0s 2ms/ste

Epoch 78/160
157/157 [==============================] - 0s 1ms/step - loss: -96563.0938 - accuracy: 0.2000
Epoch 79/160
157/157 [==============================] - 0s 1ms/step - loss: -99015.6250 - accuracy: 0.2000
Epoch 80/160
157/157 [==============================] - 0s 1ms/step - loss: -101489.2578 - accuracy: 0.2000
Epoch 81/160
157/157 [==============================] - 0s 1ms/step - loss: -103990.1328 - accuracy: 0.2000
Epoch 82/160
157/157 [==============================] - 0s 1ms/step - loss: -106525.6094 - accuracy: 0.2000
Epoch 83/160
157/157 [==============================] - 0s 1ms/step - loss: -109073.7500 - accuracy: 0.2000
Epoch 84/160
157/157 [==============================] - 0s 2ms/step - loss: -111658.0625 - accuracy: 0.2000
Epoch 85/160
157/157 [==============================] - 0s 1ms/step - loss: -114268.7578 - accuracy: 0.2000
Epoch 86/160
157/157 [==============================] - 0s 1ms/step - loss: -116924.3359 - accuracy: 0.2000
Epoch 87/160
157/157 [========

157/157 [==============================] - 0s 2ms/step - loss: -361182.0938 - accuracy: 0.2000
Epoch 154/160
157/157 [==============================] - 0s 2ms/step - loss: -365806.5000 - accuracy: 0.2000
Epoch 155/160
157/157 [==============================] - 0s 2ms/step - loss: -370458.0312 - accuracy: 0.2000
Epoch 156/160
157/157 [==============================] - 0s 2ms/step - loss: -375145.0312 - accuracy: 0.2000
Epoch 157/160
157/157 [==============================] - 0s 2ms/step - loss: -379849.2812 - accuracy: 0.2000
Epoch 158/160
157/157 [==============================] - 0s 2ms/step - loss: -384612.0000 - accuracy: 0.2000
Epoch 159/160
157/157 [==============================] - 0s 2ms/step - loss: -389393.4375 - accuracy: 0.2000
Epoch 160/160
157/157 [==============================] - 0s 1ms/step - loss: -394191.4062 - accuracy: 0.2000


In [25]:
model.save("dia_model.h5")

# ANN - MLP

In [49]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=1)

In [50]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [51]:
clf = MLPClassifier(random_state=1, max_iter=300).fit(X, y)

In [52]:
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
print("*Confusion Matrix for DT: ")
print(confusion_matrix(y_test, predictions))

*Confusion Matrix for DT: 
[[ 24  18 149  33  13]
 [ 33  19 127  48  14]
 [ 32  21 170  41  13]
 [ 24  15 144  48  14]
 [ 27  16 161  27  19]]


In [53]:
val = accuracy_score(y_test, predictions) * 100
print(val)

22.400000000000002
